config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'

  get 'flights/search'
  get 'search'   => 'flights#search'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
  end
  def search
  	require 'json'
require 'rest_client'
require 'net/http'

  	@origin = params[:from]
  	@dest = params[:to]
  	@dep_date = params[:date]
  	@adult = params[:adults]
  	@child = params[:child]
  	
@origin = @origin[0,3].upcase
@dest = @dest[0,3].upcase

org=@origin
dest=@dest
date=@dep_date

#r_date="2016-01-19"
solution=20
adult=1
child=0
senior=0

urls=[]
trip = "one way"

if trip == "one way" then
 req_param = {
  :request => {
    :slice => [
      {
        :origin => org,
        :destination => dest,
        :date => date
       # :maxStops => 0
      }
    ],
    	:passengers => {
      :adultCount => adult,
      :infantInLapCount => 0,
      :infantInSeatCount => 0,
      :childCount => child,
      :seniorCount => senior
   	 },
   	 :solutions => solution
 #  	 :refundable => false
  	}
   }.to_json
else
req_param =		{
  :request => {
    :slice => [
      {
        :origin => org,
        :destination => dest,
        :date => date,
        :maxStops => 0
      },
      {
        :origin => dest,
        :destination => org,
        :date => r_date,
        :maxStops => 0
      }
    ],
    :passengers => {
      :adultCount => adult,
      :infantInLapCount => 0,
      :infantInSeatCount => 0,
      :childCount => child,
      :seniorCount => senior
    },
     :solutions => solution
 #   :refundable => false
   }
  }.to_json
end



 
#puts req_param

@price = []
@flight_code = Array.new(100) { Array.new(100) }
@flight_number = Array.new(100) { Array.new(100) }
@cabin= Array.new(100) { Array.new(100) }
@arr_time = Array.new(100) { Array.new(100) }
@dep_time = Array.new(100) { Array.new(100) }
@seg_org= Array.new(100) { Array.new(100) }
@seg_dest = Array.new(100) { Array.new(100) }
@flight_name = []
apikey= " AIzaSyB_N9UqlXqX7eKpbK_0R1i3qnZG7awrKgU"
tempkey= "AIzaSyAx7eaVmaIJwZZa8us5QDuzwjsLopJg5K0"



@response = RestClient.post "https://www.googleapis.com/qpxExpress/v1/trips/search?key=#{apikey} ",
              req_param,
             :content_type => :json,
              :accept => :json


result = JSON.parse @response
#puts response.code

@segment_size= []
count=0


@abc = result["trips"]["data"].has_key?("airport")

if @abc == true then

result["trips"]["tripOption"].each do |sol|

     @segment_size[count] = sol["slice"][0]["segment"].size
	
	count+=1
end



k=0

result["trips"]["tripOption"].each do |sol|

	@price[k] = sol["saleTotal"]	

		 m=0
		 sol["slice"][0]["segment"].each do |seg|

	 			@flight_code[k][m] = sol["slice"][0]["segment"][m]["flight"]["carrier"]
	 				
	 				result["trips"]["data"]["carrier"].each do |x|
	 					if @flight_code[k][m] == x["code"]
	 						@flight_name[k]= x["name"]
	 					end
	 				end			

				@flight_number[k][m] = sol["slice"][0]["segment"][m]["flight"]["number"]			
				@cabin[k][m] = sol["slice"][0]["segment"][m]["cabin"]
				@arr_time[k][m] = sol["slice"][0]["segment"][m]["leg"][0]["arrivalTime"]
				@dep_time[k][m] = sol["slice"][0]["segment"][m]["leg"][0]["departureTime"]	
				@seg_org[k][m] = sol["slice"][0]["segment"][m]["leg"][0]["origin"]
				@seg_dest[k][m] = sol["slice"][0]["segment"][m]["leg"][0]["destination"]
				m+=1		
	 	 end

	k+=1
end

@avail_sol=k

citykey= "5acbf729-1e1a-469c-8f40-6899d7db5e80"


response = RestClient.get "http://iatacodes.org/api/v4/cities?api_key=#{citykey}&code=#{@origin}"

result = JSON.parse response
@origin_city = ""
result["response"].each do |i|
	if i["code"] == @origin
		@origin_city = i["name"]
	end
end

response = RestClient.get "http://iatacodes.org/api/v4/cities?api_key=#{citykey}&code=#{@dest}"

result = JSON.parse response
@dest_city = ""
result["response"].each do |i|
	if i["code"] == @dest
		@dest_city = i["name"]
	end
end

  end
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/index.html.erb
    <div id="wrap-body">
	<div class="wrapper">
        <i class="ion-android-plane plane"></i>
        <i class="ion-android-plane plane"></i>
        <h1 class="loading">Searching for flights</h1>
    </div>

 
  <div class="container">
	<div class="card-panel z-depth-5  green accent-2">
		<h3 class="center-align">Search Flights Now!!</h3>
  		<div class="row">
      		<%= form_tag(flights_search_path, method: "get", class: "col l12") do %>
      		<div class="input-field col l6">
      			   <%= text_field_tag :from, nil, id: 'autocomplete' %>
      			   <%= label_tag(:from, "From :") %>
        	</div>
      			<div class="input-field col l6">
      			   <%= text_field_tag :to, nil, id: 'autocomplete1' %>
      			   <%= label_tag(:to, "To :") %>
        	</div>
        </div>
     
        <div class="row">
      		<div class="input-field col l6">
   				 <%= date_field_tag 'date', nil, class: 'datepicker' %>
 
        	</div>
      			<div class="input-field col l3">
				  
					<%= select_tag "Adults", options_for_select([ "1", "2" , "3", "4", "5" ], "1") %>
  			    	 <%= label_tag(:adults, "Adults") %>
        		</div>
        			<div class="input-field col l3">	
      			 	<select id="child" name="child">
   				    	<option value="0">0</option>
  				    	<option value="1">1</option>
  				    	<option value="2">2</option>
   				   		<option value="3">3</option>
  			     	</select>
  			    	 <%= label_tag(:child, "Child") %>
        			</div>
        	  	
        </div>	
        		<br></br>
		
					<input class="btn-large" name="Search" type="submit" value="Search" />
			 <% end %>
		
    </div>
    <br></br>
		<br></br>
		<br></br>
		<br></br>
		<br></br>
	    <br></br>
  </div>
	

</div>
	



<!--
<div class="row card-panel green accent-2">
    <form class="col l12">
      <div class="row">
        <div class=" input-field col l6">
          <input placeholder="Placeholder" id="first_name" type="text" class="validate">
          <label for="first_name">First Name</label>
        </div>
        <div class="input-field col l6">
          <input id="last_name" type="text" class="validate">
          <label for="last_name">Last Name</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col l12">
          <input disabled value="I am not editable" id="disabled" type="text" class="validate">
          <label for="disabled">Disabled</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col l12">
          <input id="password" type="password" class="validate">
          <label for="password">Password</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col l12">
          <input id="email" type="email" class="validate">
          <label for="email">Email</label>
        </div>
      </div>
    </form>
  </div>
-->

app/views/flights/search.html.erb
<% if @abc==true then %>
<div class="row">
	<div class="col l10 offset-l1">
		<h2 class="center card-panel hoverable blue-grey darken-1 white-text"> <i> Journey From <%= @origin_city  %> to <%= @dest_city %> </i> </h2>		
	</div>
	
</div>






<div class="container">
  <% k=0 %>
	<% @avail_sol.times do %>
      <div class="row">
        <div class="col s6 m12 l12">
          <div class="card blue-grey darken-1">
            <div class="card-content ">
            	<div class="row">
            		<div class="col l6">
            			<img src="/assets/airport10.png" alt="" class="responsive-img left"><h5 class="left"> <%= @flight_name[k] %> </h5>            		
            		</div>
            		<div class="col l6">
            			<h5 class="right">Price -<%= @price[k] %></h5>		
            		</div>
            	</div>
				<% m=0 %>
		 		<% @segment_size[k].times do %>
              	<div class="row">
            		<div class="col l4">
            			<span>Flight Code- <%= @flight_code[k][m]%> </span> <br></br>
		 		   		<span>Flight Number - <%= @flight_number[k][m]%></span><br></br>
		 		   		<span>Cabin - <%= @cabin[k][m]%></span>            		
            		</div>
            		<div class="col l8">
            				<div class="row">
            					<div class="col l4">
            						<h4><%= @seg_org[k][m] %> </h4> 
            						<p>Departure Time - <%= @dep_time[k][m] %> </p>           		
            					</div>
            					<div class="col l4">
            						<img src="/assets/agt_forward.png" alt="" class="responsive-img center"> 		
            					</div>
            					<div class="col l4">
            					 	<h4> <%= @seg_dest[k][m] %>  </h4>	
            					 	<p> Arrival Time - <%= @arr_time[k][m] %> </p>	
            					</div>
            				</div>
            	  		        <br>
                   			   
            		</div>
            	</div>
		 		   		<% if m!= @segment_size[k]-1 %>
		 		   			<div class="divider"></div>
		 		   		<% end %>
		 		   	 <% m+=1 %>
		 		   <% end %>
            </div>
            <div class="card-action">
               <b><a href="#">Book Now :)</a></b>
            </div>
          </div>
        </div>
      </div>
            
    <% k+=1 %>
  <% end %>
</div>


<% else %>
<div class="white">
	<img class="materialboxed" width="60%" height="50%" src="https://css-tricks.com/images/404.jpg">
	<h2 class="text light-green accent-2"> SORRY  NO SOLUTION FOUND FOR THIS REQUEST :(</h2>
   
</div>
          
<% end %>

app/views/layouts/_footer.html.erb
 <footer class="page-footer indigo darken-4">
          <div class="footer-copyright">
            <div class="container">
            © 2015 Copyright Flight_scrapper
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
          </div>
        </footer>

app/views/layouts/_header.html.erb
  <nav>
    <div class="nav-wrapper light-blue darken-2">
      <div class="container">
          <a href="/" class="brand-logo left"> <img src="/assets/logo1.png" height="40" width="70"> Flights Search</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
              <li><a href="#!">Flights</a></li>
              <li><a href="#!">Bookings</a></li>
          </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flight Search</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body class="deep-purple lighten-5">
  <%= render 'layouts/header' %>
   
 
    	<%= yield %>
       <%= render 'layouts/footer' %>
</body>
</html>